### ISSUE TITLE
Plugin selection

### ISSUE THREAD

**Issue by ghost** [dtbaker/envato-wp-theme-setup-wizard#12]
Hi @dtbaker.

This is a really nice work. 

Is there an option to give user to choose from plugins just as like you did on importing demo content section.

And another issue is: can we use regular wordpress header and footer for this wizard. Do you know a way to achieve this.

Thank you

**Comment by dtbaker** [comment]
Thanks!

At this stage I'm not adding a plugin selection because I need all my plugins to work for the theme and demo content to install correctly. That'll just cause me issues with customer support. But it should be possible if you happy to tweak the code yourself.

It might be possible to use normal wp header/footer, but that's not something I've looked at doing sorry
